# 
name: 部署静态内容到 GitHub Pages

on:
  # 当推送到 main 分支时触发
  push:
    branches: ["main"]

  # 允许你手动在 Actions 页面点击按钮触发
  workflow_dispatch: 

# 赋予 GitHub Actions 发布 Pages 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 
# 确保不会同时进行多个部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取当前仓库
      - name: 拉取当前仓库
        uses: actions/checkout@v4

      # 2. 拉取其他仓库到临时文件夹
      - name: 拉取其他仓库到临时文件夹
        uses: actions/checkout@v4
        with:
          repository: ruchuruo/LmgzsDocs_StaticAsset
          ref: main
          path: temp_LmgzsDocs_StaticAsset

      # 3. 复制文件夹并清理临时文件夹
      - name: 复制文件夹并清理临时文件夹
        run: |
          cp -r temp_LmgzsDocs_StaticAsset/files .
          rm -rf temp_LmgzsDocs_StaticAsset

      # 4. 配置 GitHub Pages
      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v5

      # 5. 上传整个仓库作为 Pages 制品
      - name: 上传整个仓库作为 Pages 制品
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # 6. 部署到 GitHub Pages
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
